#!/usr/bin/env zsh

echo "\nHomebrew update\n"
brew update
brew upgrade
brew upgrade --cask

echo "\nAntibody update\n"
if [ -f "/opt/homebrew/opt/antidote/share/antidote/antidote.zsh" ]; then
  source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
  antidote update
fi
if [ -f "/home/mazerte/.antidote/antidote.zsh" ]; then
  source /home/mazerte/.antidote/antidote.zsh
  antidote update
fi

